
const About = () => {
  return (
    <div className="py-20 px-4 max-w-5xl mx-auto">
      <h1 className="text-3xl font-bold mb-4">About us</h1>
      <p className="mb-4 ">
        If you think all Estate Agents are the same, you have not worked with
        us. We are different. Everything we do will give you an altogether
        better experience of selling or letting your home. Our teams of local
        experts are based in 90 offices across the capital, including 15 prime
        in central London. We work hard on behalf of our clients, spending
        around 210 hours of work to find the very best buyer or tenant for every
        property we are marketing.
      </p>
      <p className="mb-4 ">
        We are in constant contact with over 130,000 people currently looking to
        move home, encouraging them to view the properties we are offering. In
        fact, 18 out of every 20 viewings are generated by our proactive
        approach, with only three viewing requests out of 20 coming from the
        internet. All this activity means we are handling up to 55,000 viewing
        appointments every month.
      </p>
      <div className="mt-10">
        <p className="mb-4">
       <span className="font-semibold">Address:</span>  123 Main St, London,  SW12 GH2
        <br />
        <span className="font-semibold">Phone:</span> (20) 456-789056
      </p></div>
  
    
    </div>
  );
}

export default About